{{ if .Values.policy.enabled }}
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: github-policy
spec:
  images:
  - glob: "**"
  authorities:
  - name: github
    keyless:
      trustRootRef: github
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subjectRegExp: https://github.com/{{ .Values.policy.organization }}/{{ .Values.policy.repo }}/\.github/workflows/.*
    rfc3161timestamp:
      trustRootRef: github
    signatureFormat: bundle
    attestations:
    - name: require-attestation
      predicateType: {{ .Values.policy.predicateType }}
  - name: public-good
    keyless:
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subjectRegExp: https://github.com/bdehamer/.*/\.github/workflows/.*
    ctlog:
      url: https://rekor.sigstore.dev
    signatureFormat: bundle
    attestations:
    - name: require-attestation
      predicateType: https://slsa.dev/provenance/v1
{{- end }}
