# A default policy can be created by setting policy.enabled to true.
policy:
  # organization is a regex that matches the organization name in the certificate identity
  organization: '.*'
  # repo is a regex that matches the repository name in the certificate identity
  repo: '.*'
  # enabled is a flag to enable the default policy
  enabled: false
  # predicateType is the type of predicate to expect in the default policy
  predicateType: https://slsa.dev/provenance/v1
  # Identify which signing authorities should be trusted as part of the policy
  trust:
    # trust the GitHub signing authority
    github: true
    # trust the Sigstore public-good signing authority
    sigstorePublic: true
