name: Release Policy Controller Chart

on:
  push:
    tags:
      - policy-controller-v*

jobs:
  release-policy-controller:
    uses: ./.github/workflows/release.yml
    with:
      chart_name: policy-controller
      chart_release: ${{ github.ref_name }}
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    secrets: inherit
