name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Package policy-controller chart
        run: helm package charts/policy-controller
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      - name: Push packaged chart to GHCR
        run: helm push policy-controller-${{ github.ref_name }}.tgz oci://${{ env.REGISTRY }}/${{ github.repository }}/policy-controller
      - name: Get pushed chart digest
        id: get-digest
        run: |
          digest=$(helm show chart oci://${{ env.REGISTRY }}/${{ github.repository }}/policy-controller --version ${{ github.ref_name }}  2>&1 >/dev/null | grep "^Digest" | sed 's/^Digest: //')
          echo digest=$digest >> $GITHUB_ENV
      - name: Attest
        uses: actions/attest-build-provenance@173725a1209d09b31f9d30a3890cf2757ebbff0d # v1.1.2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/policy-controller-${{ github.ref_name }}.tgz 
          subject-digest: ${{ steps.get-digest.outputs.digest }}
          push-to-registry: true

